#!/bin/bash -eu
set -o pipefail
log() { echo "[$(basename "$0")] $*"; }

log "Checking for empty files..."

empties="$(git ls-files | xargs -I{} -n1 bash -c '[[ -s "{}" ]] || echo "{}"')"

if [[ -n "$empties" ]]; then
  echo "$empties"
  log "!!! empty files found in source control !!!"
  exit 1
fi

log "Everything looks OK."
